const PERMISSIONS = {
  // === STRATEGIC MODULES ===

  // Strategic Maps
  ACCESS_STRATEGIC_MAPS: 'ACCESS_STRATEGIC_MAPS',
  CREATE_STRATEGIC_MAP: 'CREATE_STRATEGIC_MAP',
  READ_SINGLE_STRATEGIC_MAP: 'READ_SINGLE_STRATEGIC_MAP',
  UPDATE_STRATEGIC_MAP: 'UPDATE_STRATEGIC_MAP',
  DELETE_STRATEGIC_MAP: 'DELETE_STRATEGIC_MAP',

  // Priority Matrix
  ACCESS_PRIORITY_MATRIX: 'ACCESS_PRIORITY_MATRIX',
  MANAGE_PRIORITY_MATRIX: 'MANAGE_PRIORITY_MATRIX',

  // Stakeholders
  ACCESS_STAKEHOLDERS: 'ACCESS_STAKEHOLDERS',
  MANAGE_STAKEHOLDERS: 'MANAGE_STAKEHOLDERS',

  // Strategic Levers
  ACCESS_STRATEGIC_LEVERS: 'ACCESS_STRATEGIC_LEVERS',
  CREATE_STRATEGIC_LEVER: 'CREATE_STRATEGIC_LEVER',
  READ_STRATEGIC_LEVERS: 'READ_STRATEGIC_LEVERS',
  UPDATE_STRATEGIC_LEVER: 'UPDATE_STRATEGIC_LEVER',
  DELETE_STRATEGIC_LEVER: 'DELETE_STRATEGIC_LEVER',

  // Strategic Axes
  ACCESS_STRATEGIC_AXES: 'ACCESS_STRATEGIC_AXES',
  CREATE_STRATEGIC_AXIS: 'CREATE_STRATEGIC_AXIS',
  READ_STRATEGIC_AXES: 'READ_STRATEGIC_AXES',
  UPDATE_STRATEGIC_AXIS: 'UPDATE_STRATEGIC_AXIS',
  DELETE_STRATEGIC_AXIS: 'DELETE_STRATEGIC_AXIS',

  // Strategic Objectives
  ACCESS_STRATEGIC_OBJECTIVES: 'ACCESS_STRATEGIC_OBJECTIVES',
  CREATE_STRATEGIC_OBJECTIVE: 'CREATE_STRATEGIC_OBJECTIVE',
  READ_STRATEGIC_OBJECTIVES: 'READ_STRATEGIC_OBJECTIVES',
  UPDATE_STRATEGIC_OBJECTIVE: 'UPDATE_STRATEGIC_OBJECTIVE',
  DELETE_STRATEGIC_OBJECTIVE: 'DELETE_STRATEGIC_OBJECTIVE',

  // Alignment
  OBJ_ACCESS_ALIGNMENT: 'OBJ_ACCESS_ALIGNMENT',
  OBJ_MANAGE_ALIGNMENT: 'OBJ_MANAGE_ALIGNMENT',

  // Decisions
  OBJ_ACCESS_DECISIONS: 'OBJ_ACCESS_DECISIONS',
  OBJ_MANAGE_DECISIONS: 'OBJ_MANAGE_DECISIONS',

  // Files
  OBJ_ACCESS_FILES: 'OBJ_ACCESS_FILES',
  OBJ_MANAGE_FILES: 'OBJ_MANAGE_FILES',

  // Indicators
  ACCESS_INDICATORS: 'ACCESS_INDICATORS',
  CREATE_INDICATOR: 'CREATE_INDICATOR',
  READ_INDICATORS: 'READ_INDICATORS',
  UPDATE_INDICATOR: 'UPDATE_INDICATOR',
  DELETE_INDICATOR: 'DELETE_INDICATOR',

  // Indicator Status
  IND_ACCESS_STATUS: 'IND_ACCESS_STATUS',
  IND_MANAGE_STATUS: 'IND_MANAGE_STATUS',

  // Indicator Planning
  IND_ACCESS_PLANNING: 'IND_ACCESS_PLANNING',
  IND_MANAGE_PLANNING: 'IND_MANAGE_PLANNING',

  // Indicator Control (CRUD but no update)
  IND_ACCESS_CONTROL: 'IND_ACCESS_CONTROL',
  IND_MANAGE_CONTROL: 'IND_MANAGE_CONTROL',

  // Indicator Files
  IND_ACCESS_FILES: 'IND_ACCESS_FILES',
  IND_MANAGE_FILES: 'IND_MANAGE_FILES',

  // Indicator Decisions
  IND_ACCESS_DECISIONS: 'IND_ACCESS_DECISIONS',
  IND_MANAGE_DECISIONS: 'IND_MANAGE_DECISIONS',

  // Indicator Reporting
  IND_ACCESS_REPORTING: 'IND_ACCESS_REPORTING',

  // Action plans
  ACCESS_ACTION_PLANS: 'ACCESS_ACTION_PLANS',
  CREATE_ACTION_PLAN: 'CREATE_ACTION_PLAN',
  READ_ACTION_PLANS: 'READ_ACTION_PLANS',
  UPDATE_ACTION_PLAN: 'UPDATE_ACTION_PLAN',
  DELETE_ACTION_PLAN: 'DELETE_ACTION_PLAN',

  // Action
  ACCESS_ACTIONS: 'ACCESS_ACTIONS',
  CREATE_ACTION: 'CREATE_ACTION',
  READ_ACTIONS: 'READ_ACTIONS',
  UPDATE_ACTION: 'UPDATE_ACTION',
  DELETE_ACTION: 'DELETE_ACTION',

  // Action Status
  ACT_ACCESS_STATUS: 'ACT_ACCESS_STATUS',
  ACT_MANAGE_STATUS: 'ACT_MANAGE_STATUS',

  // Action Planning
  ACT_ACCESS_PLANNING: 'ACT_ACCESS_PLANNING',
  ACT_MANAGE_PLANNING: 'ACT_MANAGE_PLANNING',

  // Action Control
  ACT_ACCESS_CONTROL: 'ACT_ACCESS_CONTROL',
  ACT_MANAGE_CONTROL: 'ACT_MANAGE_CONTROL',

  // Action Alignment
  ACT_ACCESS_ALIGNMENT: 'ACT_ACCESS_ALIGNMENT',
  ACT_MANAGE_ALIGNMENT: 'ACT_MANAGE_ALIGNMENT',

  // Action Files
  ACT_ACCESS_FILES: 'ACT_ACCESS_FILES',
  ACT_MANAGE_FILES: 'ACT_MANAGE_FILES',

  // Action Decisions
  ACT_ACCESS_DECISIONS: 'ACT_ACCESS_DECISIONS',
  ACT_MANAGE_DECISIONS: 'ACT_MANAGE_DECISIONS',

  // Action Phases
  ACT_ACCESS_PHASES: 'ACT_ACCESS_PHASES',
  ACT_MANAGE_PHASES: 'ACT_MANAGE_PHASES',

  // Action Reporting
  ACT_ACCESS_REPORTING: 'ACT_ACCESS_REPORTING',

  // Supplier
  ACCESS_SUPPLIERS: 'ACCESS_SUPPLIERS',
  CREATE_SUPPLIER: 'CREATE_SUPPLIER',
  READ_SUPPLIERS: 'READ_SUPPLIERS',
  UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
  DELETE_SUPPLIER: 'DELETE_SUPPLIER',

  // Supplier Contracts
  SUP_ACCESS_CONTRACTS: 'SUP_ACCESS_CONTRACTS',
  SUP_MANAGE_CONTRACTS: 'SUP_MANAGE_CONTRACTS',

  // Supplier Evaluations
  SUP_ACCESS_EVALUATIONS: 'SUP_ACCESS_EVALUATIONS',
  SUP_MANAGE_EVALUATIONS: 'SUP_MANAGE_EVALUATIONS',

  // Supplier Files
  SUP_ACCESS_FILES: 'SUP_ACCESS_FILES',
  SUP_MANAGE_FILES: 'SUP_MANAGE_FILES',

  // Fund receipts
  ACCESS_FUND_RECEIPTS: 'ACCESS_FUND_RECEIPTS',
  CREATE_FUND_RECEIPT: 'CREATE_FUND_RECEIPT',
  READ_FUND_RECEIPTS: 'READ_FUND_RECEIPTS',
  UPDATE_FUND_RECEIPT: 'UPDATE_FUND_RECEIPT',
  DELETE_FUND_RECEIPT: 'DELETE_FUND_RECEIPT',

  // Fund disbursements
  ACCESS_FUND_DISBURSEMENTS: 'ACCESS_FUND_DISBURSEMENTS',
  CREATE_FUND_DISBURSEMENT: 'CREATE_FUND_DISBURSEMENT',
  READ_FUND_DISBURSEMENTS: 'READ_FUND_DISBURSEMENTS',
  UPDATE_FUND_DISBURSEMENT: 'UPDATE_FUND_DISBURSEMENT',
  DELETE_FUND_DISBURSEMENT: 'DELETE_FUND_DISBURSEMENT',

  // Structures
  ACCESS_STRUCTURES: 'ACCESS_STRUCTURES',
  CREATE_STRUCTURE: 'CREATE_STRUCTURE',
  READ_STRUCTURES: 'READ_STRUCTURES',
  UPDATE_STRUCTURE: 'UPDATE_STRUCTURE',
  DELETE_STRUCTURE: 'DELETE_STRUCTURE',

  // Employees (Personnel)
  ACCESS_EMPLOYEES: 'ACCESS_EMPLOYEES',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  READ_EMPLOYEES: 'READ_EMPLOYEES',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',

  // Action domains
  ACCESS_ACTION_DOMAINS: 'ACCESS_ACTION_DOMAINS',
  CREATE_ACTION_DOMAIN: 'CREATE_ACTION_DOMAIN',
  READ_ACTION_DOMAINS: 'READ_ACTION_DOMAINS',
  UPDATE_ACTION_DOMAIN: 'UPDATE_ACTION_DOMAIN',
  DELETE_ACTION_DOMAIN: 'DELETE_ACTION_DOMAIN',

  // Strategic domains
  ACCESS_STRATEGIC_DOMAINS: 'ACCESS_STRATEGIC_DOMAINS',
  CREATE_STRATEGIC_DOMAIN: 'CREATE_STRATEGIC_DOMAIN',
  READ_STRATEGIC_DOMAINS: 'READ_STRATEGIC_DOMAINS',
  UPDATE_STRATEGIC_DOMAIN: 'UPDATE_STRATEGIC_DOMAIN',
  DELETE_STRATEGIC_DOMAIN: 'DELETE_STRATEGIC_DOMAIN',

  // Capability domains
  ACCESS_CAPABILITY_DOMAINS: 'ACCESS_CAPABILITY_DOMAINS',
  CREATE_CAPABILITY_DOMAIN: 'CREATE_CAPABILITY_DOMAIN',
  READ_CAPABILITY_DOMAINS: 'READ_CAPABILITY_DOMAINS',
  UPDATE_CAPABILITY_DOMAIN: 'UPDATE_CAPABILITY_DOMAIN',
  DELETE_CAPABILITY_DOMAIN: 'DELETE_CAPABILITY_DOMAIN',

  // Reporting
  ACCESS_REPORTING: 'ACCESS_REPORTING',

  // System Logs
  ACCESS_LOGS: 'ACCESS_LOGS',

  // === SETTINGS ===

  // Currencies
  ACCESS_CURRENCIES: 'ACCESS_CURRENCIES',
  CREATE_CURRENCY: 'CREATE_CURRENCY',
  READ_CURRENCIES: 'READ_CURRENCIES',
  UPDATE_CURRENCY: 'UPDATE_CURRENCY',
  DELETE_CURRENCY: 'DELETE_CURRENCY',

  // Default Phases
  ACCESS_DEFAULT_PHASES: 'ACCESS_DEFAULT_PHASES',
  CREATE_DEFAULT_PHASE: 'CREATE_DEFAULT_PHASE',
  UPDATE_DEFAULT_PHASE: 'UPDATE_DEFAULT_PHASE',
  DELETE_DEFAULT_PHASE: 'DELETE_DEFAULT_PHASE',

  // File Types
  ACCESS_FILE_TYPES: 'ACCESS_FILE_TYPES',
  CREATE_FILE_TYPE: 'CREATE_FILE_TYPE',
  READ_FILE_TYPES: 'READ_FILE_TYPES',
  UPDATE_FILE_TYPE: 'UPDATE_FILE_TYPE',
  DELETE_FILE_TYPE: 'DELETE_FILE_TYPE',

  // Contract Types
  ACCESS_CONTRACT_TYPES: 'ACCESS_CONTRACT_TYPES',
  CREATE_CONTRACT_TYPE: 'CREATE_CONTRACT_TYPE',
  READ_CONTRACT_TYPES: 'READ_CONTRACT_TYPES',
  UPDATE_CONTRACT_TYPE: 'UPDATE_CONTRACT_TYPE',
  DELETE_CONTRACT_TYPE: 'DELETE_CONTRACT_TYPE',

  // Procurement Modes
  ACCESS_PROCUREMENT_MODES: 'ACCESS_PROCUREMENT_MODES',
  CREATE_PROCUREMENT_MODE: 'CREATE_PROCUREMENT_MODE',
  READ_PROCUREMENT_MODES: 'READ_PROCUREMENT_MODES',
  UPDATE_PROCUREMENT_MODE: 'UPDATE_PROCUREMENT_MODE',
  DELETE_PROCUREMENT_MODE: 'DELETE_PROCUREMENT_MODE',

  // Project Owners
  ACCESS_PROJECT_OWNERS: 'ACCESS_PROJECT_OWNERS',
  CREATE_PROJECT_OWNER: 'CREATE_PROJECT_OWNER',
  READ_PROJECT_OWNERS: 'READ_PROJECT_OWNERS',
  UPDATE_PROJECT_OWNER: 'UPDATE_PROJECT_OWNER',
  DELETE_PROJECT_OWNER: 'DELETE_PROJECT_OWNER',

  // Delegated Project Owners
  ACCESS_DELEGATED_PROJECT_OWNERS: 'ACCESS_DELEGATED_PROJECT_OWNERS',
  CREATE_DELEGATED_PROJECT_OWNER: 'CREATE_DELEGATED_PROJECT_OWNER',
  READ_DELEGATED_PROJECT_OWNERS: 'READ_DELEGATED_PROJECT_OWNERS',
  UPDATE_DELEGATED_PROJECT_OWNER: 'UPDATE_DELEGATED_PROJECT_OWNER',
  DELETE_DELEGATED_PROJECT_OWNER: 'DELETE_DELEGATED_PROJECT_OWNER',

  // Funding Sources
  ACCESS_FUNDING_SOURCES: 'ACCESS_FUNDING_SOURCES',
  CREATE_FUNDING_SOURCE: 'CREATE_FUNDING_SOURCE',
  READ_FUNDING_SOURCES: 'READ_FUNDING_SOURCES',
  UPDATE_FUNDING_SOURCE: 'UPDATE_FUNDING_SOURCE',
  DELETE_FUNDING_SOURCE: 'DELETE_FUNDING_SOURCE',

  // Regions
  ACCESS_REGIONS: 'ACCESS_REGIONS',
  CREATE_REGION: 'CREATE_REGION',
  READ_REGIONS: 'READ_REGIONS',
  UPDATE_REGION: 'UPDATE_REGION',
  DELETE_REGION: 'DELETE_REGION',

  // Departments
  ACCESS_DEPARTMENTS: 'ACCESS_DEPARTMENTS',
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  READ_DEPARTMENTS: 'READ_DEPARTMENTS',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',

  // Municipalities
  ACCESS_MUNICIPALITIES: 'ACCESS_MUNICIPALITIES',
  CREATE_MUNICIPALITY: 'CREATE_MUNICIPALITY',
  READ_MUNICIPALITIES: 'READ_MUNICIPALITIES',
  UPDATE_MUNICIPALITY: 'UPDATE_MUNICIPALITY',
  DELETE_MUNICIPALITY: 'DELETE_MUNICIPALITY',

  // Beneficiaries
  ACCESS_BENEFICIARIES: 'ACCESS_BENEFICIARIES',
  CREATE_BENEFICIARY: 'CREATE_BENEFICIARY',
  READ_BENEFICIARIES: 'READ_BENEFICIARIES',
  UPDATE_BENEFICIARY: 'UPDATE_BENEFICIARY',
  DELETE_BENEFICIARY: 'DELETE_BENEFICIARY',

  // Payment Modes
  ACCESS_PAYMENT_MODES: 'ACCESS_PAYMENT_MODES',
  CREATE_PAYMENT_MODE: 'CREATE_PAYMENT_MODE',
  READ_PAYMENT_MODES: 'READ_PAYMENT_MODES',
  UPDATE_PAYMENT_MODE: 'UPDATE_PAYMENT_MODE',
  DELETE_PAYMENT_MODE: 'DELETE_PAYMENT_MODE',

  // Budget Types
  ACCESS_BUDGET_TYPES: 'ACCESS_BUDGET_TYPES',
  CREATE_BUDGET_TYPE: 'CREATE_BUDGET_TYPE',
  READ_BUDGET_TYPES: 'READ_BUDGET_TYPES',
  UPDATE_BUDGET_TYPE: 'UPDATE_BUDGET_TYPE',
  DELETE_BUDGET_TYPE: 'DELETE_BUDGET_TYPE',

  // Expense Types
  ACCESS_EXPENSE_TYPES: 'ACCESS_EXPENSE_TYPES',
  CREATE_EXPENSE_TYPE: 'CREATE_EXPENSE_TYPE',
  READ_EXPENSE_TYPES: 'READ_EXPENSE_TYPES',
  UPDATE_EXPENSE_TYPE: 'UPDATE_EXPENSE_TYPE',
  DELETE_EXPENSE_TYPE: 'DELETE_EXPENSE_TYPE',

  // Indicator Categories
  ACCESS_INDICATOR_CATEGORIES: 'ACCESS_INDICATOR_CATEGORIES',
  CREATE_INDICATOR_CATEGORY: 'CREATE_INDICATOR_CATEGORY',
  READ_INDICATOR_CATEGORIES: 'READ_INDICATOR_CATEGORIES',
  UPDATE_INDICATOR_CATEGORY: 'UPDATE_INDICATOR_CATEGORY',
  DELETE_INDICATOR_CATEGORY: 'DELETE_INDICATOR_CATEGORY',

  // === USERS ===
  ACCESS_USERS: 'ACCESS_USERS',
  CREATE_USER: 'CREATE_USER',
  READ_USERS: 'READ_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // === ROLES ===
  ACCESS_ROLES: 'ACCESS_ROLES',
  CREATE_ROLE: 'CREATE_ROLE',
  READ_ROLES: 'READ_ROLES',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
};

export default PERMISSIONS;
